"use client";

/* eslint-disable @next/next/no-img-element -- the admin mockup reuses checked-in catalog photography. */

import Link from "next/link";
import {
  Activity, ArrowRight, BarChart3, Bell, BookOpen, Boxes, ChevronDown, ChevronRight,
  CircleGauge, ClipboardList, ExternalLink, GraduationCap, HeartHandshake, Home,
  Layers3, Megaphone, Menu, MessageSquare, PackageCheck, PlugZap, Search, Settings,
  ShoppingBag, Sparkles, Store, Users, X,
} from "lucide-react";
import { useMemo, useState, type ComponentType } from "react";
import { articles, brandById, communitySeedPosts, courseDuration, courseLessonCount, courses, formatRsd, products } from "@/lib/data";
import { productPhotoFor } from "@/components/product-photo";

type AdminView = "home" | "orders" | "products" | "inventory" | "customers" | "content" | "academy" | "community" | "marketing" | "analytics" | "erp";
type NavItem = { id: AdminView; label: string; icon: ComponentType<{ size?: number }>; badge?: string };

const navGroups: Array<{ label: string; items: NavItem[] }> = [
  { label: "Prodaja", items: [
    { id: "home", label: "Početna", icon: Home }, { id: "orders", label: "Porudžbine", icon: ShoppingBag, badge: "7" },
    { id: "products", label: "Proizvodi", icon: Boxes }, { id: "inventory", label: "Zalihe", icon: Layers3, badge: "4" },
    { id: "customers", label: "Kupci", icon: Users },
  ] },
  { label: "Iskustvo", items: [
    { id: "content", label: "Sadržaj", icon: BookOpen }, { id: "academy", label: "Akademija", icon: GraduationCap },
    { id: "community", label: "Zajednica", icon: MessageSquare }, { id: "marketing", label: "Marketing", icon: Megaphone },
    { id: "analytics", label: "Analitika", icon: BarChart3 },
  ] },
  { label: "Sistemi", items: [{ id: "erp", label: "ERP & CRM", icon: PlugZap, badge: "Live" }] },
];

const viewTitle: Record<AdminView, string> = { home: "Početna", orders: "Porudžbine", products: "Proizvodi", inventory: "Zalihe", customers: "Kupci", content: "Sadržaj", academy: "Akademija", community: "Zajednica", marketing: "Marketing", analytics: "Analitika", erp: "ERP & CRM" };
const mockOrders = [
  { number: "#1048", customer: "Milica Petrović", status: "Za obradu", total: 9180, payment: "Plaćeno", items: 3, date: "Pre 8 min" },
  { number: "#1047", customer: "Sara Ilić", status: "Spremno", total: 12960, payment: "Pouzećem", items: 4, date: "Danas, 09:18" },
  { number: "#1046", customer: "Ana Radović", status: "Poslato", total: 6680, payment: "Plaćeno", items: 2, date: "Juče, 16:05" },
  { number: "#1045", customer: "Jovana Nikolić", status: "Isporučeno", total: 8970, payment: "Plaćeno", items: 3, date: "Juče, 12:27" },
  { number: "#1044", customer: "Nina Lukić", status: "Isporučeno", total: 2990, payment: "Plaćeno", items: 1, date: "26. avg" },
];

export default function AdminPage() {
  const [view, setView] = useState<AdminView>("home");
  const [navOpen, setNavOpen] = useState(false);
  function select(next: AdminView) { setView(next); setNavOpen(false); window.scrollTo({ top: 0, behavior: "smooth" }); }

  return <div className="admin-mockup">
    <header className="admin2-topbar">
      <button className="admin2-menu" onClick={() => setNavOpen(true)} aria-label="Otvori admin navigaciju"><Menu /></button>
      <button className="admin2-store-switch"><span>E</span><strong>EQUA Serbia</strong><ChevronDown size={15} /></button>
      <label className="admin2-global-search"><Search size={16} /><input placeholder="Pretraži porudžbine, proizvode i kupce" aria-label="Pretraži administraciju" /><kbd>⌘ K</kbd></label>
      <div className="admin2-top-actions"><span className="admin2-demo-pill">Interaktivni mockup</span><button aria-label="Obaveštenja"><Bell size={18} /><i /></button><button className="admin2-user">AT</button></div>
    </header>
    <div className="admin2-shell">
      <aside className={`admin2-sidebar ${navOpen ? "is-open" : ""}`}>
        <div className="admin2-mobile-head"><strong>EQUA admin</strong><button onClick={() => setNavOpen(false)} aria-label="Zatvori navigaciju"><X /></button></div>
        <nav aria-label="Admin sekcije">{navGroups.map((group) => <div className="admin2-nav-group" key={group.label}><span>{group.label}</span>{group.items.map((item) => <button className={view === item.id ? "is-active" : ""} onClick={() => select(item.id)} key={item.id}><item.icon size={18} /><strong>{item.label}</strong>{item.badge && <small>{item.badge}</small>}</button>)}</div>)}</nav>
        <div className="admin2-sidebar-foot"><Link href="/" target="_blank"><Store size={18} /><strong>Online prodavnica</strong><ExternalLink size={14} /></Link><button><Settings size={18} /><strong>Podešavanja</strong></button></div>
      </aside>
      {navOpen && <button className="admin2-nav-backdrop" onClick={() => setNavOpen(false)} aria-label="Zatvori admin navigaciju" />}
      <div className="admin2-main">
        <header className="admin2-page-head"><div><p>EQUA / {viewTitle[view]}</p><h1>{viewTitle[view]}</h1></div><button className="admin2-primary">{view === "orders" ? "Kreiraj porudžbinu" : view === "products" ? "Dodaj proizvod" : view === "content" ? "Novi vodič" : "Prilagodi prikaz"}</button></header>
        {view === "home" && <HomeView onNavigate={select} />}{view === "orders" && <OrdersView />}{view === "products" && <ProductsView />}{view === "inventory" && <InventoryView onNavigate={select} />}{view === "customers" && <CustomersView />}{view === "content" && <ContentView />}{view === "academy" && <AcademyView />}{view === "community" && <CommunityView />}{view === "marketing" && <MarketingView />}{view === "analytics" && <AnalyticsView />}{view === "erp" && <ErpView />}
      </div>
    </div>
  </div>;
}

function HomeView({ onNavigate }: { onNavigate: (view: AdminView) => void }) { return <>
  <section className="admin2-metrics"><Metric label="Ukupna prodaja" value="4.078.000 RSD" delta="+18,4%" /><Metric label="Porudžbine" value="148" delta="+12,1%" /><Metric label="Konverzija" value="4,8%" delta="+0,7 pp" /><Metric label="Prosečna korpa" value="8.940 RSD" delta="−2,3%" down /></section>
  <section className="admin2-home-grid"><article className="admin2-card admin2-attention"><CardHead icon={Sparkles} eyebrow="Sledeće akcije" title="Danas traži pažnju" /><ActionRow tone="lime" icon={PackageCheck} title="7 porudžbina čeka obradu" meta="Najstarija pre 42 minuta" onClick={() => onNavigate("orders")} /><ActionRow tone="peach" icon={Boxes} title="4 proizvoda ima nisku zalihu" meta="1 proizvod trenutno nije dostupan" onClick={() => onNavigate("inventory")} /><ActionRow tone="lilac" icon={MessageSquare} title="3 nova community pitanja" meta="Prosečan odgovor eksperta 2h 14m" onClick={() => onNavigate("community")} /></article><article className="admin2-card admin2-sales-card"><CardHead icon={Activity} eyebrow="Poslednjih 7 dana" title="Prodaja kroz vreme" /><div className="admin2-spark-chart">{[42,58,49,71,63,91,74,105,88,122,96,138].map((height, index) => <i style={{ height }} key={index} />)}</div><div className="admin2-sales-total"><span>Neto prodaja</span><strong>4.078.000 RSD</strong></div></article></section>
  <section className="admin2-card admin2-list-card"><CardHead icon={ShoppingBag} eyebrow="Operativa" title="Nedavne porudžbine" action={<button onClick={() => onNavigate("orders")}>Prikaži sve <ArrowRight /></button>} /><OrderTable rows={mockOrders.slice(0, 4)} /></section>
</>; }

function OrdersView() { return <section className="admin2-card admin2-list-card"><ListToolbar placeholder="Pretraži porudžbine" filters={["Sve", "Neispunjene", "Otvorene", "Zatvorene"]} /><OrderTable rows={mockOrders} /></section>; }
function ProductsView() { return <section className="admin2-card admin2-list-card"><ListToolbar placeholder="Pretraži proizvode" filters={["Sve", "Aktivno", "Draft", "Arhivirano"]} /><div className="admin2-table-wrap"><table className="admin2-table admin2-product-table"><thead><tr><th>Proizvod</th><th>Status</th><th>Zaliha</th><th>Kategorija</th><th>Cena</th></tr></thead><tbody>{products.slice(0, 10).map((product) => <tr key={product.id}><td><div className="admin2-product"><img src={productPhotoFor(product)} alt="" /><span><strong>{product.name}</strong><small>{brandById[product.brandId].name} · {product.size}</small></span></div></td><td><Status tone="green">Aktivno</Status></td><td>{product.stock.quantity} na stanju</td><td>{product.category.replaceAll("-", " ")}</td><td>{formatRsd(product.priceRsd)}</td></tr>)}</tbody></table></div></section>; }
function InventoryView({ onNavigate }: { onNavigate: (view: AdminView) => void }) { const low = useMemo(() => products.filter((product) => product.stock.quantity <= 20).sort((a, b) => a.stock.quantity - b.stock.quantity), []); return <><section className="admin2-callout"><div><Boxes /><span><strong>ERP upravlja glavnim stanjem zaliha.</strong>Finalna verzija šalje validirane korekcije kroz integration hub.</span></div><button onClick={() => onNavigate("erp")}>Otvori ERP sync <ArrowRight /></button></section><section className="admin2-card admin2-list-card"><ListToolbar placeholder="Pretraži SKU ili proizvod" filters={["Sve lokacije", "Niska zaliha", "Nema na stanju"]} /><div className="admin2-table-wrap"><table className="admin2-table"><thead><tr><th>Proizvod</th><th>SKU</th><th>Dostupno</th><th>Rezervisano</th><th>Dolazi</th><th>Status</th></tr></thead><tbody>{low.map((product, index) => <tr key={product.id}><td><strong>{product.name}</strong></td><td>EQ-{product.id.slice(0, 6).toUpperCase()}</td><td>{product.stock.quantity}</td><td>{index + 1}</td><td>{index % 2 ? 24 : "—"}</td><td><Status tone={product.stock.quantity === 0 ? "red" : "yellow"}>{product.stock.quantity === 0 ? "Nema" : "Nisko"}</Status></td></tr>)}</tbody></table></div></section></>; }
function CustomersView() { const customers = [{ name: "Milica Petrović", orders: 6, spent: 42890, blueprint: "Mirna barijera" },{ name: "Sara Ilić", orders: 4, spent: 28670, blueprint: "Age support" },{ name: "Ana Radović", orders: 3, spent: 21420, blueprint: "Duboka hidratacija" },{ name: "Jovana Nikolić", orders: 2, spent: 15310, blueprint: "Glow bez iritacije" }]; return <><section className="admin2-metrics admin2-metrics--three"><Metric label="Ukupno kupaca" value="1.284" delta="+96 ovog meseca" /><Metric label="Povratni kupci" value="28,6%" delta="+4,2 pp" /><Metric label="Članovi sa Blueprintom" value="742" delta="58% baze" /></section><section className="admin2-card admin2-list-card"><ListToolbar placeholder="Pretraži kupce" filters={["Svi", "VIP", "Novi", "Bez porudžbine"]} /><div className="admin2-table-wrap"><table className="admin2-table"><thead><tr><th>Kupac</th><th>Skin Blueprint</th><th>Porudžbine</th><th>Ukupna potrošnja</th></tr></thead><tbody>{customers.map((customer) => <tr key={customer.name}><td><strong>{customer.name}</strong></td><td>{customer.blueprint}</td><td>{customer.orders}</td><td>{formatRsd(customer.spent)}</td></tr>)}</tbody></table></div></section></>; }
function ContentView() { return <section className="admin2-card admin2-list-card"><CardHead icon={BookOpen} eyebrow="Content hub" title={`${articles.length} vodiča`} /><div className="admin2-content-grid">{articles.slice(0, 6).map((article) => <article key={article.id}><img src={article.image} alt="" /><div><Status tone="green">Objavljeno</Status><h2>{article.title}</h2><p>{article.category.replaceAll("-", " ")} · {article.readingMinutes} min</p></div><button aria-label={`Otvori ${article.title}`}><ChevronRight /></button></article>)}</div></section>; }
function AcademyView() { return <section className="admin2-card admin2-list-card"><CardHead icon={GraduationCap} eyebrow="Learning commerce" title="Programi i lekcije" /><div className="admin2-course-grid">{courses.map((course) => <article key={course.id}><img src={course.image} alt="" /><div><Status tone="green">Objavljeno</Status><h2>{course.title}</h2><p>{courseLessonCount(course)} lekcija · {courseDuration(course)} min</p><span>{course.priceRsd === 0 ? "Besplatno" : formatRsd(course.priceRsd)}</span></div><button>Uredi <ChevronRight /></button></article>)}</div></section>; }
function CommunityView() { return <><section className="admin2-metrics admin2-metrics--three"><Metric label="Aktivni članovi" value="1.284" delta="+8,4%" /><Metric label="Prijavljeni sadržaj" value="0,6%" delta="niska stopa" /><Metric label="Odgovor eksperta" value="2h 14m" delta="prosek" /></section><section className="admin2-card admin2-list-card"><CardHead icon={MessageSquare} eyebrow="Moderacija" title="Poslednje teme" /><div className="admin2-table-wrap"><table className="admin2-table"><thead><tr><th>Tema</th><th>Autor</th><th>Prostor</th><th>Odgovori</th><th>Status</th></tr></thead><tbody>{communitySeedPosts.map((post) => <tr key={post.id}><td><strong>{post.title}</strong></td><td>{post.authorName}</td><td>{post.spaceId}</td><td>{post.replies}</td><td><Status tone="green">Objavljeno</Status></td></tr>)}</tbody></table></div></section></>; }
function MarketingView() { const flows = [["Welcome serija", "Registracija ili newsletter", "Aktivan", "38,4% open rate"],["Napuštena korpa", "Korpa bez kupovine · 2h", "Aktivan", "12 vraćenih korpi"],["Post-purchase", "3 dana posle isporuke", "Aktivan", "31 novih recenzija"],["Win-back", "Bez kupovine · 75 dana", "Draft", "Čeka CRM segment"]]; return <><section className="admin2-callout admin2-callout--lilac"><div><HeartHandshake /><span><strong>CRM automations mockup</strong>Kupovina, Skin Blueprint, kurs i loyalty događaji ulaze u isti profil kupca.</span></div><button>Nova automatizacija</button></section><section className="admin2-card admin2-list-card"><CardHead icon={Megaphone} eyebrow="Lifecycle" title="Automatizovani flow-ovi" /><div className="admin2-automation-grid">{flows.map(([name, trigger, status, result]) => <article key={name}><span><Activity /></span><h2>{name}</h2><p>{trigger}</p><Status tone={status === "Aktivan" ? "green" : "gray"}>{status}</Status><small>{result}</small></article>)}</div></section></>; }
function AnalyticsView() { return <><section className="admin2-metrics"><Metric label="Online sesije" value="2.840" delta="+16,1%" /><Metric label="Završen Skin Check" value="384" delta="13,5% sesija" /><Metric label="Academy activation" value="61%" delta="članova" /><Metric label="Repeat rate" value="28,6%" delta="+4,2 pp" /></section><section className="admin2-card admin2-analytics"><CardHead icon={BarChart3} eyebrow="Problem → sadržaj → proizvod" title="Konverzioni put" /><div className="admin2-funnel">{[["Posete","100%","2.840"],["Skin Check","76%","1.114"],["Preporuka","52%","842"],["Korpa","29%","381"],["Kupovina","13%","148"]].map(([label,width,value]) => <div key={label}><span>{label}</span><i style={{ width }} /><strong>{value}</strong></div>)}</div></section></>; }
function ErpView() { const syncRows = [["Porudžbina #1048", "Webshop → ERP", "Uspešno", "Pre 3 min"],["Zalihe · 24 SKU", "ERP → Webshop", "Uspešno", "Pre 7 min"],["Cenovnik RS-RSD", "ERP → Webshop", "Uspešno", "Pre 18 min"],["Kupac · Milica Petrović", "Webshop → CRM", "Uspešno", "Pre 22 min"],["Nabavka PO-228", "ERP → Webshop", "Čeka", "Pre 31 min"]]; return <><section className="admin2-erp-hero"><div><span className="admin2-erp-icon"><PlugZap /></span><p className="eyebrow">ERP Core · sandbox</p><h2>Svi operativni podaci, jedan tok.</h2><p>Mockup integracionog centra za narudžbine, cene, zalihe, nabavku, računovodstvo i CRM profile.</p><div className="admin2-erp-status"><i /> Poslednja uspešna sinhronizacija pre 3 min</div></div><button>Pokreni ručni sync</button></section><section className="admin2-sync-flow"><div><Store /><span><strong>EQUA webshop</strong>Porudžbine · članovi · kviz</span></div><i><ArrowRight /></i><div className="is-hub"><PlugZap /><span><strong>Integration hub</strong>Validacija · retry · logovi</span></div><i><ArrowRight /></i><div><CircleGauge /><span><strong>ERP + CRM</strong>Zalihe · cene · kupci</span></div></section><section className="admin2-metrics admin2-metrics--three"><Metric label="Sinhronizacija danas" value="1.842" delta="99,8% uspešno" /><Metric label="Red za ponovni pokušaj" value="3" delta="automatski retry" /><Metric label="Prosečno kašnjenje" value="42 sec" delta="ispod cilja" /></section><section className="admin2-card admin2-list-card"><CardHead icon={ClipboardList} eyebrow="Integration log" title="Poslednje razmene" action={<button>Dokumentacija <ExternalLink /></button>} /><div className="admin2-table-wrap"><table className="admin2-table"><thead><tr><th>Zapis</th><th>Tok</th><th>Status</th><th>Vreme</th></tr></thead><tbody>{syncRows.map(([record, direction, status, time]) => <tr key={record}><td><strong>{record}</strong></td><td>{direction}</td><td><Status tone={status === "Uspešno" ? "green" : "yellow"}>{status}</Status></td><td>{time}</td></tr>)}</tbody></table></div></section></>; }

function Metric({ label, value, delta, down = false }: { label: string; value: string; delta: string; down?: boolean }) { return <article><span>{label}</span><strong>{value}</strong><small className={down ? "is-down" : ""}>{delta}</small></article>; }
function Status({ children, tone }: { children: React.ReactNode; tone: "green" | "yellow" | "red" | "gray" }) { return <span className={`admin2-status admin2-status--${tone}`}>{children}</span>; }
function CardHead({ icon: Icon, eyebrow, title, action }: { icon: ComponentType<{ size?: number }>; eyebrow: string; title: string; action?: React.ReactNode }) { return <div className="admin2-card-head"><span><Icon size={18} /></span><div><small>{eyebrow}</small><h2>{title}</h2></div>{action && <div className="admin2-card-action">{action}</div>}</div>; }
function ActionRow({ icon: Icon, title, meta, tone, onClick }: { icon: ComponentType<{ size?: number }>; title: string; meta: string; tone: string; onClick: () => void }) { return <button className="admin2-action-row" onClick={onClick}><span className={`is-${tone}`}><Icon /></span><div><strong>{title}</strong><small>{meta}</small></div><ChevronRight /></button>; }
function ListToolbar({ placeholder, filters }: { placeholder: string; filters: string[] }) { return <div className="admin2-list-toolbar"><label><Search /><input placeholder={placeholder} /></label><div>{filters.map((filter, index) => <button className={index === 0 ? "is-active" : ""} key={filter}>{filter}</button>)}</div><button className="admin2-filter-button"><Layers3 /> Filteri</button></div>; }
function OrderTable({ rows }: { rows: typeof mockOrders }) { return <div className="admin2-table-wrap"><table className="admin2-table"><thead><tr><th>Porudžbina</th><th>Datum</th><th>Kupac</th><th>Plaćanje</th><th>Isporuka</th><th>Stavke</th><th>Ukupno</th></tr></thead><tbody>{rows.map((order) => <tr key={order.number}><td><strong>{order.number}</strong></td><td>{order.date}</td><td>{order.customer}</td><td><Status tone="green">{order.payment}</Status></td><td><Status tone={order.status === "Za obradu" ? "yellow" : order.status === "Poslato" ? "gray" : "green"}>{order.status}</Status></td><td>{order.items}</td><td><strong>{formatRsd(order.total)}</strong></td></tr>)}</tbody></table></div>; }
